
/**
 * 📅 GOOGLE CALENDAR LINK GENERATOR
 * Generates a direct link to create an event in Google Calendar.
 */

const formatDateForGoogle = (dateIso: string): string => {
    const date = new Date(dateIso);
    // Format: YYYYMMDDTHHMMSSZ
    return date.toISOString().replace(/-|:|\.\d{3}/g, '');
};

export const openInGoogleCalendar = (
    title: string, 
    description: string = '', 
    startTimeIso?: string, 
    durationMinutes: number = 60
) => {
    if (!startTimeIso) {
        alert("تاريخ غير محدد لهذه المهمة.");
        return;
    }

    const start = new Date(startTimeIso);
    const end = new Date(start.getTime() + durationMinutes * 60000);

    const startStr = formatDateForGoogle(start.toISOString());
    const endStr = formatDateForGoogle(end.toISOString());

    const details = encodeURIComponent(`${description}\n\nGenerated by LifeOS`);
    const summary = encodeURIComponent(`[LifeOS] ${title}`);
    const location = encodeURIComponent("LifeOS HQ");

    const url = `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${summary}&dates=${startStr}/${endStr}&details=${details}&location=${location}`;

    window.open(url, '_blank');
};
